{{- if not .Values.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: rallly
  labels:
    {{- include "rallly.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.secret.databaseUrl | b64enc }}
  SECRET_PASSWORD: {{ .Values.secret.secretPassword | b64enc }}
  OIDC_CLIENT_ID: {{ .Values.secret.oidcClientId | b64enc }}
  OIDC_CLIENT_SECRET: {{ .Values.secret.oidcClientSecret | b64enc }}
{{- end }}
