apiVersion: v1
kind: Service
metadata:
  name: rallly
  labels:
    {{- include "rallly.labels" . | nindent 4 }}
    component: rallly
spec:
  selector:
    stack: rallly
    component: rallly
  ports:
    - port: 3000
      targetPort: 3000
