name: cicd

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: qb-arc-runners
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    environment: production
    steps:
      - uses: actions/checkout@v7
      - uses: azure/setup-helm@v5
      - run: |
          helm upgrade --install rallly chart \
            --namespace rallly \
            -f chart/values-production.yaml \
            --wait --timeout 300s
